Cadastro de autor
erikamarchi/casa-do-codigo-demo pull request #7
Opened 2019-11-25 14:59 UTC by erikamarchi

resolve #3

2019-11-25 15:01 UTC, erikamarchi commented
Está faltando a validação de forma mais amigável

2019-11-25 17:02 UTC, asouza approved these changes
Esse pr foi  incrível, nem tenho o que falar :). Deixei só um comentário, coisa ultra pequena. Queria até conversar com você para entender ainda melhor como você construiu e utilizou alguns conhecimentos do pr... optional, mapper etc...

2019-11-25 17:02 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/AutorDao.java
> +			Optional<Autor> autor;
aqui você pode começar com Optional.empty() e matar o else do rs.next :).

2019-11-25 18:25 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/AutorDao.java
> +			Optional<Autor> autor;
Feito :)

2019-11-27 02:03 UTC, erikamarchi commented
@asouza a implementação está finalizada, espero o seu code review :)

2019-11-27 20:12 UTC, asouza requested changes
Oi Erika, esse review foi mais focado no lance de proteger as bordas da aplicação. Temos sempre que nos preocupar em validar os parâmetros de entrada de nossos métodos, dessa forma aumentamos a chance de não cairmos em bugs mais simples como nullpointer, listas vazias etc.

2019-11-27 20:12 UTC, asouza commented on casa-do-codigo/src/main/webapp/WEB-INF/views/autor/form.jsp
> +	<script>
Aqui foi legal o código js, mas, nesse momento, vamos focar em controlar a validação do lado do backend apenas. A validaçao no lado do cliente ajuda para dar retorno rápido, mas no fim, o que conta é a proteção que você tem no lado do servidor. Vamos atacar lá primeiro :).

2019-11-27 20:12 UTC, asouza commented on casa-do-codigo/src/main/webapp/WEB-INF/views/autor/form.jsp
> +			<input id="nome" type="text" name="nome" class="form-control" required value="${autor.nome}">
pode deixar sem o required, para a gente ter oportunidade de capturar o erro no lado do servidor

2019-11-27 20:12 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/autor/AutorMapper.java
> +		String nome = validaParametro(request, "nome");
Opa, aqui é uma questão interessante. Não sei se já te falei, mas acho que um bom jeito de pensar nos métodos é como se eles fossem bordas do sistema. E o método deve ser muito criterioso para deixar qualquer valor passar por lá... Todo parâmetro de entrada, idealmente, deveria ser validado mesmo. E aí, se ele chegar com um valor inválido, você realmente deve soltar exception... Pq isso, geralmente, caracteriza um bug. O único momento que isso não é bug, é se o método for aquele chamado inicialmente em função da requisição do usuário. Pq aí não controlamos o que o usuário digita ou deixa de digitar :). 

Dado esse textão, é ok você os valores aqui dentro em carater de programação defensiva, mas tende a ficar confuso se você quiser pegar os erros e enviar de volta para o usuário de alguma forma.

2019-11-27 20:12 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/autor/AutorMapper.java
> +		return Optional
Aqui é só um ponto de atenção hehe. Pelo seu post, eu entendi que você gostou muito da Option. Por outro lado, aqui parece que aqui o código ficou um pouco mais complicado de entender do que era necessário. Tem method reference e lambdas para verificarmos  se o valor ta preenchido.

2019-11-27 20:12 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/autor/ManipulaAutorServlet.java
> +			throws ServletException, IOException {
pensando no lance da borda, a primeira coisa que você fazer é verificar se as restrições dos parâmetros foram atendidas :). E aí, caso não tenham sido, você tem a oportunidade de voltar para a tela de cadastro informando os erros. Dessa forma você sabe que daí para baixo ta tudo bem.

2019-11-27 20:56 UTC, erikamarchi commented on casa-do-codigo/src/main/webapp/WEB-INF/views/autor/form.jsp
> +	<script>
@asouza Eu tinha pensado em 3 camadas de proteção: 
1. no banco de dados;
2. no mapper do mundo externo para o meu modelo; e
3. no cliente. 

Aí pensei que para o cliente é legal ter uma mensagem amigável, mas se o usuário (hacker) que está alterando na mão e enviando para o backend, simplesmente lanço uma exceção. Aí estruturei o código para funcionar desse jeito. Inclusive, eu estava tirando o 'required' na mão para testar a proteção do backend hahahah

Vou reestruturar para fazer a validação com os retornos para o cliente vindo do backend, aí eu concordo com tudo que vc falou :D

2019-11-30 23:44 UTC, erikamarchi commented
@asouza fiz a implementação da validação que vc sugeriu e acabei fazendo mais algumas refatorações, fico esperando o seu review :)

2019-12-01 09:49 UTC, asouza requested changes
Oi Erika, seu código está muito rico. Caso você se sinta melhor durante essa semana, podemos marcar de conversar pessoalmente sobre o pr? Terça seria um bom dia. Segunda(amanhã) pode rolar também, mas tenho uma palestra as 16 no itam que bagunçou meu dia. 

Eu pedi mudanças apenas para saber o que você pensa sobre os questionamentos que deixei :).

2019-12-01 09:49 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/AutorDao.java
> +	public Optional<Autor> getPorNome(String nome) {
e se vierem dois autores com o mesmo nome?

2019-12-01 09:49 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/autor/RegistroDoAutorHandler.java
> +			onSuccess.accept(autorDao, autorDto.toModel());
Aqui tem uma divisão de responsabilidade que me gerou dúvidas. Pq o handler não pode salvar o autor? Você já tinha o dao, já tinha o objeto que sabe criar um autor em função dos parâmetros e tudo mais. Fiquei curioso.

2019-12-02 18:19 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/AutorDao.java
> +	public Optional<Autor> getPorNome(String nome) {
Para respeitar a restrição de que dois autores não podem ter o mesmo nome, estou fazendo essa validação tanto na criação quando na edição. Caso o usuário tente cadastrar, aparecerá uma mensagem avisando que ele deve informar outro nome.

2019-12-03 01:00 UTC, merged