Implementa crud de categoria
erikamarchi/casa-do-codigo-demo pull request #9
Opened 2019-12-05 00:59 UTC by erikamarchi

resolve #8

2019-12-05 01:01 UTC, erikamarchi commented
@asouza tentei implementar essa feature levando em consideração o que conversamos :D

2019-12-05 10:17 UTC, asouza requested changes
Ficou ótimo! As abstrações foram usadas na medida certa, proporcional ao nível de dificuldade do código :). Não montamos a tabela de pontuação, mas ficou bem mais de boa. Deixei apenas uns desafios para você :).

2019-12-05 10:17 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/CategoriaDao.java
> +	public void exclui(Categoria categoria) {
aqui um desafio :). Para excluir uma categoria precisamos de um objeto completo? Da forma que está, provavelmente, a pessoa carregaria uma categoria para memória para chamar o exclui. O que podemos fazer para facilitar?

2019-12-05 10:17 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaValidator.java
> +public class CategoriaValidator {
Aqui você tem um desafio. Temos misturado a validação das informações básicas de uma categoria com uma validação que não tem necessariamente a ver com "este" objeto em si. O nome dele não está em branco e está com menos de 30 caracteres, ou seja, ele não está inválido. A validação de nome duplicado, é uma validação que é mais uma constraint do sistema(negócio) do que do objeto em si. Como você pode fazer para separar isso em duas validações?

2019-12-05 10:17 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaController.java
> +		Optional<String> erroNome = CategoriaValidator.valida(categoriaDto, categoriaDao);
Esse código de validação já é bem parecido com o primeiro. E a validação é uma coisa que você vai fazer pelo sistema todo... Será que conseguimos criar alguma abstração maior para representar os erros de validação e acessá-los lá no formulário? Já pensa também que um mesmo formulário pode ter mais de um erro de validação :). Aqui estou adiantando um pouco, para ficarmos mais preparados para o cadastro de um livro.

2019-12-06 15:52 UTC, erikamarchi commented
@asouza refatorei o crud de categoria e tentei não complicar muito hahaha

2019-12-06 22:46 UTC, asouza requested changes
Deixei um dilema no fim para você. A maior parte está tranquila, tem alguns pontos que serão desafiadores para a próxima feature. Falamos quando deixarmos esse todo certinho.

2019-12-06 22:46 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/CategoriaDao.java
> +	public void exclui(Long id) {
Eu gosto assim, acho que facilita. Só para registrar, você vai encontrar no mercado alguém te dizendo que precisa passar uma categoria, já que nosso código é orientado a objetos e o seu dao abstrai o fato de acessarmos um banco de dados e não sei o que lá mais... Uma outra solução talvez mais elegante do ponto de vista alheio era termos uma interface assim:

```
interface HasDatabaseId {
   public Long getId();
}
```
Todo mundo que tem id de banco de dados implementa e você poderia receber um parametro desse tipo aí. Dessa forma, a semântica ficava ainda mais clara que precisa receber que seja um id de banco. Acho muita abstração para uma coisa tão simples.

2019-12-06 22:46 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaComIdController.java
> +			categoria.ifPresent(c ->
você pode trocar o nome da variável categoria para possivelCategoria e de c para categoria :)

2019-12-06 22:46 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaError.java
> +			String erroNome = null;
Você pode começar com um Optional.empty e trocar caso exista o erro. Aí você evita o ternario lá embaixo. O ternário, em geral, tende a ser um código menos comum e um pouco mais complicado de entender.

2019-12-06 22:46 UTC, asouza commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaErrorHandler.java
> +		request.setAttribute("categoria", categoriaDto);
E se alguém chamar um setAttribute nessa request depois que chamaram o onFail? Quando você altera o estado de uma referência que chegou como argumento fica um pouco mais complicado de seguir o caminho do código. A ideia é que você só altere estado de objetos que você criou. A exceção é quando a referência é passada para você por algum framework ou lib desconhecida, tipo quando o HttpServletRequest chega como argumento lá no servlet. 

Tenta resolver esse dilema?

2019-12-06 23:56 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/dao/CategoriaDao.java
> +	public void exclui(Long id) {
Legal :)
Vou criar uma issue com isso

2019-12-07 00:04 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaErrorHandler.java
> +		request.setAttribute("categoria", categoriaDto);
eliminei onFail, mas realmente não sei como melhorar esse código de forma simples :)

2019-12-07 00:05 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaError.java
> +			String erroNome = null;
Feito :)

2019-12-07 00:14 UTC, erikamarchi commented on casa-do-codigo/src/main/java/br/com/caelum/casadocodigo/servlet/categoria/CategoriaController.java
> +		Optional<String> erroNome = CategoriaValidator.valida(categoriaDto, categoriaDao);
Separei regra de form de regra de negócio. Apesar de eu não trabalhar com lista de erros, estou trabalhando com uma classe que representa todos os campos que possuem validação, assim, se tiver varias validações, eu retorno a mensagem correspondente para cada campo. Tentei fazer uma abstração simples, já que a outra forma que eu tinha pensado era com annotation e reflection :)

2019-12-07 11:37 UTC, erikamarchi commented
@asouza vê se agora aparece

2019-12-08 09:15 UTC, asouza approved these changes
Imagino que quando você estava copiando o request.setAttribute deve ter dado uma coceira na mão heee. Por outro lado, realmente agora fica fácil de entender as variáveis que estão disponíveis na página :). Nem sempre o que se repete, necessariamente precisa ser isolado.. a não ser que seja de uma forma que não perca a semantica da coisa.

2019-12-08 09:17 UTC, asouza commented
Agora vamos para o post relativo a essa issue. Você teve algumas coisas aqui: muita abstração x pouca abstração, mudar referências que não foram criadas por você, generalizar validação etc. Minha sugestão é pegar o primeiro ou segundo tema. Se tiver outra ideia, não deixe de falar :).

2019-12-09 12:07 UTC, merged